### ISSUE TITLE
PvP 1.8(?)

### ISSUE THREAD

**Issue by NovaPixell** [joeShuff/UHCBasePlugin#1]
Hi, nice plugin! I'm having the following problem: PvP of 1.8 appears to be activated with your plugin. That is, there is no cooldown on each item. it's normal?

**Comment by joeShuff** [comment]
Hi Nova, sorry for the late reply, wasn't expecting activity on this plugin yet as I'm still working on it.

You are right, it does seem to be 1.8 pvp by default, that's my mistake! I am migrating one of my older plugins from many years ago and this one thing slipped through the cracks!

I will address this now by adding it as a config option and get it merged into master shortly. You will have to build yourself for now as I need to do some full game tests before I release any versions.

Thanks for pointing that out!

**Comment by NovaPixell** [comment]
Don't worry. I miss readed your README, xD
I advise you one thing. Could you speed up the teleport, for example teleporting 10 players in 1 second?
Yesterday I hosted 100 players and it took him 2 minutes to teleport them all

**Comment by joeShuff** [comment]
Oh wow I didn't expect this to be used for such big UHCs yet, I hope it did a good job 😛 

Regarding the teleporting, could you create a seperate issue about it on github so I've got a trail of issues and it can be discussed there, thanks!

**Comment by NovaPixell** [comment]
ok!

**Comment by joeShuff** [comment]
This has been resolved and added as a config item `1-8-pvp`. Only merged into `develop` for now as I'd like to run some bigger scale test before I create a release but feel free to build locally.
