### ISSUE TITLE
Speedup Player Teleporting

### ISSUE THREAD

**Issue by NovaPixell** [joeShuff/UHCBasePlugin#2]

**Comment by joeShuff** [comment]
Currently what happens is:
A timer exists counting every second and does the following on each second.
1st Second -> notify who is being teleported (team or player) 
2nd Second -> Start loading the chunks in a 5x5 radius around the teleport location. This could take a bit of time hence the delay until the...
8th Second ->Teleports all the players to this location.

My main concern is with the loading of chunks, I will do some investigating of other options and do a bit of refactoring to be able to introduce a config item like `bulk-teleport` to be able to say how many people/teams to teleport at once so it can be toned in and out for smaller/larger UHCs.

I really appreciate all feedback you can give to make this plugin better for all. 😄

**Comment by joeShuff** [comment]
I have now modified the teleporting and added 2 new config options.
`teleport-size` - how many players get teleported in 1 batch
`teleport-delay` - how many seconds between each batch of teleports. It is recommended to keep this around 4s to allow the server to not get overloaded, but there is no limits.

Changes in develop as of [this commit](https://github.com/joeShuff/UHCBasePlugin/commit/c7f6cd76c0451520dba4b9f771da7f22102dfa1a)
